from config import (
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    LOG_DIR,
    AZURE_CONTAINER_NAME,
)

print("RAW DATA:", RAW_DATA_DIR)
print("PROCESSED DATA:", PROCESSED_DATA_DIR)
print("LOG DIR:", LOG_DIR)
print("AZURE CONTAINER:", AZURE_CONTAINER_NAME)